### ISSUE TITLE
occur error 500 when call jsonrpc:omni_createpayload_simplesend in node.js

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omnicore#674]
When I call jsonrpc-api:omni_createpayload_simplesend in node.js ,I often got 500 error:

Here is my code

> 'use strict';
> const RpcClient = require('node-json-rpc2').Client;
> const config = {
>     protocol:'http',//Optional. Will be http by default
>     host:'127.0.0.1',//Will be 127.0.0.1 by default
>     user:'omnicorerpc',//Optional, only if auth needed
>     password:'5hMTZI9iBGFqKxsWfOUF',//Optional. Can be named 'pass'. Mandatory if user is passed.
>     port:8332,//Will be 8443 for https or 8080 for http by default
>     method:'POST'//Optional. POST by default
> };
>                 var client = new RpcClient(config);
> 
>                 //构造发送代币类型和代币数量数据（payload）
>                 client.call({
>                     method:'omni_createpayload_simplesend',//Mandatory
>                     params:[31,'"'+amount+'"'],//Will be [] by default
>                     id:'rpcExample',//Optional. By default it's a random id
>                     jsonrpc:'2.0'//Optional. By default it's 2.0
>                 },(err, res_payload)=>{
>                     if(err){
>                         //Do something
>                         console.log(err);
>                         var obj = {
>                             "success": false,
>                             "error_no": 2,
>                             "error_info": "omni_createpayload_simplesend failed!"
>                         }
>                         res.jsonp(obj);
>                     } else {
>                         console.log('Data:',res_payload.result);//Json parsed.
>                         res.jsonp(res_payload.result);
> 
>                         var payload = res_payload.result;
> 
>                         
>                         
>                     }
>                     
>                 });

and here is my error info printed on console:
```

> Error: Connection Rejected : 500 Internal server error
>     at IncomingMessage.<anonymous> (/etc/projects/tether/OmniClientJS/node_modules/node-json-rpc2/lib/client.js:105:25)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

```
I'm confused that if I call this api by cmd,It's ok,such as below:

> # ./omnicore-cli -conf=/etc/usdt/bitcoin.conf  "omni_createpayload_simplesend" 31 0.0002
> 000000000000001f0000000000004e20

I can get right result.
And when I call other api(such as dumpprivkey),I can also get right result,such as below:

> var client = new RpcClient(config);
>             client.call({
>                 method:'dumpprivkey',//Mandatory
>                 params:[new_addr],//Will be [] by default
>                 id:'rpcExample',//Optional. By default it's a random id
>                 jsonrpc:'2.0'//Optional. By default it's 2.0
>             },(err, res_generUSDTAddressfinal)=>{
>                 if(err){
>                    //Do something
>                    var obj = {
>                         "success": false,
>                         "error_no": 12,
>                         "error_info": "get priv key failed!"
>                     }
>                 } else {
>                     var privkey = res_generUSDTAddressfinal.result;
>                     var obj_generUSDTAddress = {
>                         "success": true,
>                         "generated_address": new_addr,
>                         "privkey": privkey
>                     }
>                     res_generUSDTAddress.jsonp(obj_generUSDTAddress);
> 
> 
>                 }
> 
>             });

So the only question is that why I can't call "omni_createpayload_simplesend"

Can anyone help me？thanks a lot！

**Comment by dexX7** [comment]
Hi there, do you submit the amount as string?

**Comment by tangjielong** [comment]
client.cmd('omni_createpayload_simplesend',2,"0.1", function(err, hashs) {
    if (err) return console.log(err);
    console.log('hashs:', hashs);
);
can run it
